### ISSUE TITLE
Blog post image links are broken

### ISSUE THREAD

**Issue by ebubekirtrkr** [blacknbunny/blacknbunny.github.io#2]
The images that using resmim.net are broken. If u have images, could you fix it? I have read almost every blog post and looking forward to fixing this issue.

**Comment by blacknbunny** [comment]
You can make commits i will accept all of it no cap.

**Comment by blacknbunny** [comment]
And also if you have opinions to make this blog more beautiful i will accept those too again no cap.

**Comment by ebubekirtrkr** [comment]
I suppose you get me wrong. For example in the [rootkit-development-part-1](https://blacknbunny.github.io/2019/05/29/rootkit-development-part-1.html) page the images hosted at resmin.net and they are not accessible. Here is the example image [https://resmim.net/f/DMcOWo.jpg](https://resmim.net/f/DMcOWo.jpg). If I have images I just commit them already.

**Comment by blacknbunny** [comment]
But that's the thing ain't got pics... If you want to add any images of yours, I would be happy to add them. Actually if you do this you will save the blog from death.

**Comment by ebubekirtrkr** [comment]
I'll try to add <3
